Algoritmo "semnome"
// Descrição   : Calcular a base e altura de um triangulo
// Autor(a)    : Caio Maranhao
Var
// Seção de Declarações das variáveis 
altura:inteiro
base:inteiro
resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a altura do triangulo: ")
leia (altura}
escreva("Digite a base do triangulo: ")
leia (base)
resultado<-(base*altura)/(2)
escreval("Resultado: ",resultado)
Fimalgoritmo